# Generated by Django 3.2 on 2021-11-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='TaskList',
        ),
    ]
