# Generated by Django 3.2 on 2021-10-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('BatchId', models.AutoField(primary_key=True, serialize=False)),
                ('BatchName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=500)),
                ('Age', models.IntegerField(max_length=2)),
                ('JoiningDate', models.DateField()),
            ],
        ),
    ]
