# Generated by Django 3.2 on 2021-10-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='BatchName',
            field=models.CharField(default='Math', max_length=500),
        ),
    ]
